vim.cmd.colorscheme('vim')
local function hl(name, val) vim.api.nvim_set_hl(0, name, val) end
hl("Type", { fg = '#007f00', italic = true })
hl("Structure", { fg = '#009f5f', italic = true })
hl("Constant", { fg = '#ff6000' })
hl("String", { fg = '#ff9f9f' })
hl("Special", { fg = '#ffafff', italic = true })

hl("@attribute", { link = "Macro" })
hl("@attribute.builtin", { link = "Special" })
hl("@boolean", { link = "Boolean" })
hl("@character", { link = "Character" })
hl("@character.special", { link = "SpecialChar" })
hl("@comment", { link = "Comment" })
hl("@comment.error", { link = "DiagnosticError" })
hl("@comment.note", { link = "DiagnosticInfo" })
hl("@comment.todo", { link = "Todo" })
hl("@comment.warning", { link = "DiagnosticWarn" })
hl("@constant", { link = "Constant" })
hl("@constant.builtin", { link = "Special" })
hl("@constant.macro", { link = "Define" })
hl("@constructor", { link = "Special" })
hl("@diff.delta", { link = "Changed" })
hl("@diff.minus", { link = "Removed" })
hl("@diff.plus", { link = "Added" })
hl("@function", { link = "Function" })
hl("@function.builtin", { link = "Special" })
hl("@function.macro", { link = "Macro" })
hl("@function.method", { link = "Function" })
hl("@keyword", { link = "Keyword" })
hl("@keyword.conditional", { link = "Conditional" })
hl("@keyword.debug", { link = "Debug" })
hl("@keyword.directive", { link = "PreProc" })
hl("@keyword.exception", { link = "Exception" })
hl("@keyword.import", { link = "Include" })
hl("@keyword.repeat", { link = "Repeat" })
hl("@keyword.type", { link = "Structure" })
hl("@label", { link = "Label" })
hl("@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hl("@lsp.type.class", { link = "Structure" })
hl("@lsp.type.comment", { link = "Comment" })
hl("@lsp.type.decorator", { link = "Function" })
hl("@lsp.type.enum", { link = "Structure" })
hl("@lsp.type.enumMember", { fg = '#ff7f9f'})
hl("@lsp.type.event", { link = "@type" })
hl("@lsp.type.function", { fg = '#2fffff' })
hl("@lsp.type.interface", { link = "Structure" })
hl("@lsp.type.keyword", { link = "@keyword" })
hl("@lsp.type.macro", { fg = '#9fffff', bold = true })
hl("@lsp.type.method", { fg = '#5fffff' })
hl("@lsp.type.modifier", { link = "@type.qualifier" })
hl("@lsp.type.namespace", { link = "Structure" })
hl("@lsp.type.number", { link = "@number" })
hl("@lsp.type.operator", { fg = '#afffaf', bold = true })
hl("@lsp.type.parameter", { fg = '#afafaf', bold = true })
hl("@lsp.type.property", { fg = '#6fefcf' })
hl("@lsp.type.regexp", { link = "@string.regexp" })
hl("@lsp.type.string", { link = "@string" })
hl("@lsp.type.struct", { link = "Structure" })
hl("@lsp.type.type", { link = "Type" })
hl("@lsp.type.typeParameter", { link = "Typedef" })
hl("@lsp.type.variable", { fg = '#00afcf' })
hl("@markup", { link = "Special" })
hl("@markup.heading", { link = "Title" })
hl("@markup.heading.1.delimiter.vimdoc",
	{ bg = 0, cterm = { nocombine = true, underdouble = true }, fg = 0, nocombine = true, sp = 14342874, underdouble = true })
hl("@markup.heading.2.delimiter.vimdoc",
	{ bg = 0, cterm = { nocombine = true, underline = true }, fg = 0, nocombine = true, sp = 14342874, underline = true })
hl("@markup.italic", { cterm = { italic = true }, italic = true })
hl("@markup.link", { link = "Identifier" })
hl("@markup.link.url", { link = "Underlined" })
hl("@markup.raw", { link = "Comment" })
hl("@markup.strikethrough", { cterm = { strikethrough = true }, strikethrough = true })
hl("@markup.strong", { bold = true, cterm = { bold = true } })
hl("@markup.underline", { link = "Underlined" })
hl("@module", { link = "Identifier" })
hl("@module.builtin", { link = "Special" })
hl("@number", { link = "Number" })
hl("@number.float", { link = "Float" })
hl("@operator", { link = "Operator" })
hl("@property", { link = "Identifier" })
hl("@punctuation", { link = "Delimiter" })
hl("@punctuation.special", { link = "Special" })
hl("@string", { link = "String" })
hl("@string.escape", { link = "SpecialChar" })
hl("@string.regexp", { link = "@string.special" })
hl("@string.special", { link = "SpecialChar" })
hl("@string.special.url", { link = "Underlined" })
hl("@tag", { link = "Tag" })
hl("@tag.builtin", { link = "Special" })
hl("@type", { link = "Type" })
hl("@type.builtin", { link = "Special" })
hl("@type.definition", { link = "Typedef" })
hl("@variable", { link = "Identifier" })
hl("@variable.builtin", { link = "Special" })
hl("@variable.member", { link = "Identifier" })
hl("@variable.parameter", { link = "Identifier" })
hl("@variable.parameter.builtin", { link = "Special" })
