local kmp = vim.keymap
kmp.set('n', '<A-h>', '<C-w>h')
kmp.set('n', '<A-j>', '<C-w>j')
kmp.set('n', '<A-k>', '<C-w>k')
kmp.set('n', '<A-l>', '<C-w>l')

kmp.set('n', 't', ':sp\n:terminal\na')
kmp.set('t', '<esc>', '')

kmp.set("n", "<space>e", vim.diagnostic.open_float)
kmp.set("n", "[d", vim.diagnostic.goto_prev)
kmp.set("n", "]d", vim.diagnostic.goto_next)
kmp.set("n", "<space>q", vim.diagnostic.setloclist)

kmp.set('v', '<', '<gv')
kmp.set('v', '>', '>gv')
kmp.set('v', '<C-S-A>', '<esc>O/*<esc>gvo<esc>o*/<esc>')
kmp.set('v', '<C-S-C>', '<esc>ddgvo<esc>dd')
kmp.set("n", "gD", vim.lsp.buf.declaration)
kmp.set("n", "gd", vim.lsp.buf.definition)
kmp.set("n", "K", vim.lsp.buf.hover)
kmp.set("n", "gi", vim.lsp.buf.implementation)
kmp.set("n", "<C-k>", vim.lsp.buf.signature_help)
kmp.set("n", "<space>wa", vim.lsp.buf.add_workspace_folder)
kmp.set("n", "<space>wr", vim.lsp.buf.remove_workspace_folder)
kmp.set("n", "<space>wl", function()
	print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
end)
kmp.set("n", "<space>D", vim.lsp.buf.type_definition)
kmp.set("n", "<space>rn", vim.lsp.buf.rename)
kmp.set({ "n", "v" }, "<space>ca", vim.lsp.buf.code_action)
kmp.set("n", "gr", vim.lsp.buf.references)
kmp.set("n", "<space>f", function()
	vim.lsp.buf.format({ async = true })
end)
