local opt = vim.o

opt.autoindent = true
opt.autoread = true
opt.backup = false
opt.clipboard = 'unnamedplus'
opt.cursorline = true
opt.expandtab = false
opt.laststatus = 0
opt.linebreak = true
opt.number = true
opt.relativenumber = true
opt.scrolloff = 12
opt.shiftwidth = 8
opt.showcmd = true
opt.softtabstop = 8
opt.splitbelow = true
opt.splitright = true
opt.swapfile = false
opt.tabstop = 8
opt.termguicolors = true
opt.undofile = true
