vim.opt.autoindent = true
vim.opt.autoread = true
vim.opt.backup = false
vim.opt.cindent = true
vim.opt.clipboard = 'unnamedplus'
vim.opt.cursorline = true
vim.opt.endofline = false
vim.opt.expandtab = false
vim.opt.laststatus = 0
vim.opt.list = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.scrolloff = 12
vim.opt.shiftwidth = 4
vim.opt.showcmd = true
vim.opt.softtabstop = 4
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.tabstop = 4
vim.opt.termguicolors = true
vim.opt.undofile = true
vim.opt.fileencodings = { "utf-8", "utf-16le", "utf-16", "sjis", "gb18030", "big5", "euc-jp", "latin1" }

vim.wo.wrap = true
vim.wo.linebreak = true
vim.wo.breakindent = true
